INSERT INTO User (name, url, phone, email, create_at, update_at)
VALUES ('aaaa aaaa', 'https://aaa.com', '000-0000-0000', 'aaa@aaa.com', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('bbbb bbbb', 'https://bbb.com', '111-1111-1111', 'bbb@bbb.com', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('cccc cccc', 'https://ccc.com', '222-2222-2222', 'ccc@ccc.com', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('dddd dddd', 'https://ddd.com', '333-3333-3333', 'ddd@ddd.com', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('eeee eeee', 'https://eee.com', '444-4444-4444', 'eee@eee.com', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('ffff ffff', 'https://fff.com', '555-5555-5555', 'fff@fff.com', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('gggg gggg', 'https://ggg.com', '666-6666-6666', 'ggg@ggg.com', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('hhhh hhhh', 'https://hhh.com', '777-7777-7777', 'hhh@hhh.com', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('iiii iiii', 'https://iii.com', '888-8888-8888', 'iii@iii.com', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('jjjj jjjj', 'https://jjj.com', '999-9999-9999', 'jjj@jjj.com', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('kkkk kkkk', 'https://kkk.com', '***-****-****', 'kkk@kkk.com', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('llll llll', 'https://lll.com', '***-****-****', 'lll@lll.com', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('mmmm mmmm', 'https://mmm.com', '***-****-****', 'mmm@mmm.com', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('nnnn nnnn', 'https://nnn.com', '***-****-****', 'nnn@nnn.com', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('oooo oooo', 'https://ooo.com', '***-****-****', 'ooo@ooo.com', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('pppp pppp', 'https://ppp.com', '***-****-****', 'ppp@ppp.com', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('qqqq qqqq', 'https://qqq.com', '***-****-****', 'qqq@qqq.com', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('rrrr rrrr', 'https://rrr.com', '***-****-****', 'rrr@rrr.com', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('ssss ssss', 'https://sss.com', '***-****-****', 'sss@sss.com', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('tttt tttt', 'https://ttt.com', '***-****-****', 'ttt@ttt.com', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('uuuu uuuu', 'https://uuu.com', '***-****-****', 'uuu@uuu.com', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('vvvv vvvv', 'https://vvv.com', '***-****-****', 'vvv@vvv.com', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('wwww wwww', 'https://www.com', '***-****-****', 'www@www.com', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('xxxx xxxx', 'https://xxx.com', '***-****-****', 'xxx@xxx.com', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('yyyy yyyy', 'https://yyy.com', '***-****-****', 'yyy@yyy.com', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('zzzz zzzz', 'https://zzz.com', '***-****-****', 'zzz@zzz.com', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
