INSERT INTO User (name, url, phone, email, create_at, update_at)
VALUES ('aaaa aaaa', 'aaa.com', '000-0000-0000', 'aaa@aaa.com', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('bbbb bbbb', 'bbb.com', '111-1111-1111', 'bbb@bbb.com', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('cccc cccc', 'ccc.com', '222-2222-2222', 'ccc@ccc.com', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('dddd dddd', 'ddd.com', '333-3333-3333', 'ddd@ddd.com', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('eeee eeee', 'eee.com', '444-4444-4444', 'eee@eee.com', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('ffff ffff', 'fff.com', '555-5555-5555', 'fff@fff.com', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('gggg gggg', 'ggg.com', '666-6666-6666', 'ggg@ggg.com', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('hhhh hhhh', 'hhh.com', '777-7777-7777', 'hhh@hhh.com', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('iiii iiii', 'iii.com', '888-8888-8888', 'iii@iii.com', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('jjjj jjjj', 'jjj.com', '999-9999-9999', 'jjj@jjj.com', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('kkkk kkkk', 'kkk.com', '***-****-****', 'kkk@kkk.com', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('llll llll', 'lll.com', '***-****-****', 'lll@lll.com', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('mmmm mmmm', 'mmm.com', '***-****-****', 'mmm@mmm.com', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('nnnn nnnn', 'nnn.com', '***-****-****', 'nnn@nnn.com', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('oooo oooo', 'ooo.com', '***-****-****', 'ooo@ooo.com', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('pppp pppp', 'ppp.com', '***-****-****', 'ppp@ppp.com', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('qqqq qqqq', 'qqq.com', '***-****-****', 'qqq@qqq.com', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('rrrr rrrr', 'rrr.com', '***-****-****', 'rrr@rrr.com', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('ssss ssss', 'sss.com', '***-****-****', 'sss@sss.com', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('tttt tttt', 'ttt.com', '***-****-****', 'ttt@ttt.com', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('uuuu uuuu', 'uuu.com', '***-****-****', 'uuu@uuu.com', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('vvvv vvvv', 'vvv.com', '***-****-****', 'vvv@vvv.com', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('wwww wwww', 'www.com', '***-****-****', 'www@www.com', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('xxxx xxxx', 'xxx.com', '***-****-****', 'xxx@xxx.com', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('yyyy yyyy', 'yyy.com', '***-****-****', 'yyy@yyy.com', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('zzzz zzzz', 'zzz.com', '***-****-****', 'zzz@zzz.com', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
