CREATE TABLE IF NOT EXISTS User (
  id INTEGER NOT NULL AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL,
  url VARCHAR(255) NOT NULL,
  phone VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  create_at DATETIME NOT NULL,
  update_at DATETIME NOT NULL,
  PRIMARY KEY (id)
);