name: CI Local Test

# Disabled on GitHub Actions.
on: workflow_call

env:
  NODE_VERSION: 22.*
  YARN_VERSION: 4.6.0

jobs:
  setup:
    name: Setup Module
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Execution Environment for Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Cache Node Modules
        id: node_modules_cache_id
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-v${{ env.NODE_VERSION }}-deps-${{ hashFiles(format('{0}{1}', github.workspace, '/yarn.lock')) }}
          restore-keys: |
            ${{ runner.os }}-node-v${{ env.NODE_VERSION }}-deps-
      - name: Set Yarn Version
        run: |
          corepack enable
          yarn set version ${{ env.YARN_VERSION }}
      - name: Install Dependencies
        run: yarn

  cspell:
    name: CSpell
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Execution Environment for Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Set Yarn Version
        run: |
          corepack enable
          yarn set version ${{ env.YARN_VERSION }}
      - name: Restore Modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-v${{ env.NODE_VERSION }}-deps-${{ hashFiles(format('{0}{1}', github.workspace, '/yarn.lock')) }}
      - uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest
      - name: Do CSpell
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          yarn cspell --dot --no-must-find-files "**/*" \
          | reviewdog -level=warning -efm="%f:%l:%c - %m" -reporter=github-pr-review
      - name: Displayed CSpell Failure on Checks
        run: yarn cspell --dot --no-must-find-files "**/*"

  eslintApps:
    name: ESlint Apps
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Execution Environment for Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Set Yarn Version
        run: |
          corepack enable
          yarn set version ${{ env.YARN_VERSION }}
      - name: Restore Modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-v${{ env.NODE_VERSION }}-deps-${{ hashFiles(format('{0}{1}', github.workspace, '/yarn.lock')) }}
      - name: Do ESLint Apps
        uses: reviewdog/action-eslint@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          workdir: "apps"
          eslint_flags: "./**/*.{ts,mjs,js}"
      - name: Displayed ESLINT Failure on Checks
        run: yarn lint:apps

  eslintClient:
    name: ESlint Client
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Execution Environment for Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Set Yarn Version
        run: |
          corepack enable
          yarn set version ${{ env.YARN_VERSION }}
      - name: Restore Modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-v${{ env.NODE_VERSION }}-deps-${{ hashFiles(format('{0}{1}', github.workspace, '/yarn.lock')) }}
      - name: Do ESLint Client
        uses: reviewdog/action-eslint@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          workdir: "client"
          eslint_flags: "./**/*.{ts,mjs,js}"
      - name: Displayed ESLINT Failure on Checks
        run: yarn lint:client

  stylelint:
    name: Stylelint
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Execution Environment for Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Set Yarn Version
        run: |
          corepack enable
          yarn set version ${{ env.YARN_VERSION }}
      - name: Restore Modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-v${{ env.NODE_VERSION }}-deps-${{ hashFiles(format('{0}{1}', github.workspace, '/yarn.lock')) }}
      - name: Do Stylelint
        uses: reviewdog/action-stylelint@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          stylelint_input: "./**/*.scss"
      - name: Displayed Stylelint Failure on Checks
        run: yarn stylelint

  typecheckApps:
    name: Type Check Apps
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Execution Environment for Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Set Yarn Version
        run: |
          corepack enable
          yarn set version ${{ env.YARN_VERSION }}
      - name: Restore Modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-v${{ env.NODE_VERSION }}-deps-${{ hashFiles(format('{0}{1}', github.workspace, '/yarn.lock')) }}
      # Currently, tsc && reviewdog is will not display properly in conversation review.
      - name: Do Type Check Apps
        uses: EPMatt/reviewdog-action-tsc@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          workdir: apps
          level: warning
          fail_on_error: true
          filter_mode: nofilter
      # - name: Displayed Tsc Failure on Checks
      #   if: env.LAUNCH_TYPECHECK == 'on'
      #   run: yarn typecheck:apps

  typecheckClient:
    name: Type Check Client
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Execution Environment for Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Set Yarn Version
        run: |
          corepack enable
          yarn set version ${{ env.YARN_VERSION }}
      - name: Restore Modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-v${{ env.NODE_VERSION }}-deps-${{ hashFiles(format('{0}{1}', github.workspace, '/yarn.lock')) }}
      # Currently, tsc && reviewdog is will not display properly in conversation review.
      - name: Do Type Check Client
        uses: EPMatt/reviewdog-action-tsc@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          workdir: client
          level: warning
          fail_on_error: true
          filter_mode: nofilter
      # - name: Displayed Tsc Failure on Checks
      #   if: env.LAUNCH_TYPECHECK == 'on'
      #   run: yarn typecheck:client

  build:
    name: Build Test
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Execution Environment for Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Set Yarn Version
        run: |
          corepack enable
          yarn set version ${{ env.YARN_VERSION }}
      - name: Restore Modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-v${{ env.NODE_VERSION }}-deps-${{ hashFiles(format('{0}{1}', github.workspace, '/yarn.lock')) }}
      - name: Install Global Gulp For Client.
        run: yarn workspace client add global gulp-cli
      - name: Do Build Test
        run: yarn build
